[package]
name = "fullscreen-dim"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ddc = "0.2.2"
ddc-i2c = { version="0.2.2", features=["with-linux", "with-linux-enumerate"] }
